author: "mitulmlakhani99@gmail.com"
category: "http"
summary: "HTTP POST user's messages with extensions to target URL when user is offline for eJabberd version >= 17.01"
home: "https://github.com/mitulmlakhani/mod_offline_http_post_ext"
url: "https://github.com/mitulmlakhani/mod_offline_http_post_ext"